name: one_bataan_league_pass_common

version: 0.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging: ^0.11.4
  flutter_appcenter_bundle: ^1.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0
  mockito: ^4.1.1
